<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ContainerTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * MÓDULO 3: VIAJES Y CARGAS
     * Seeder para tipos de contenedor según estándares ISO
     * 100% coherente con migración create_container_types_table.php
     */
    public function run(): void
    {
        $now = Carbon::now();

        $containerTypes = [
            // 1. CONTENEDOR 20GP
            [
                'code' => '20GP',
                'name' => 'Contenedor 20 pies General Purpose',
                'short_name' => '20GP',
                'description' => 'Contenedor estándar de 20 pies para carga general',
                'iso_code' => '22G1',
                'iso_size_type' => '22G1',
                'iso_group' => 'general',
                'length_feet' => '20',
                'width_feet' => '8',
                'height_feet' => '8.5',
                'length_mm' => 6058.00,
                'width_mm' => 2438.00,
                'height_mm' => 2591.00,
                'internal_length_mm' => 5898.00,
                'internal_width_mm' => 2352.00,
                'internal_height_mm' => 2393.00,
                'tare_weight_kg' => 2230.00,
                'max_gross_weight_kg' => 30480.00,
                'max_payload_kg' => 28250.00,
                'internal_volume_m3' => 33.20,
                'loading_volume_m3' => 32.50,
                'category' => 'dry_cargo',
                'is_refrigerated' => false,
                'is_heated' => false,
                'is_insulated' => false,
                'is_ventilated' => false,
                'has_electrical_supply' => false,
                'has_roof' => true,
                'has_sidewalls' => true,
                'has_end_walls' => true,
                'has_doors' => true,
                'has_removable_top' => false,
                'has_folding_sides' => false,
                'door_type' => 'standard',
                'door_width_mm' => 2340.00,
                'door_height_mm' => 2280.00,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'has_humidity_control' => false,
                'has_atmosphere_control' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_food' => true,
                'suitable_for_chemicals' => false,
                'suitable_for_liquids' => false,
                'suitable_for_bulk_cargo' => false,
                'suitable_for_heavy_cargo' => true,
                'suitable_for_oversized_cargo' => false,
                'requires_special_handling' => false,
                'requires_power_supply' => false,
                'requires_ventilation' => false,
                'requires_monitoring' => false,
                'stackable' => true,
                'max_stack_height' => 9,
                'csc_certified' => true,
                'food_grade' => true,
                'pharmaceutical_grade' => false,
                'certifications' => json_encode(['CSC', 'ISO']),
                'typical_lifespan_years' => 15,
                'inspection_interval_months' => 12,
                'requires_pretrip_inspection' => true,
                'requires_cleaning' => true,
                'requires_fumigation' => false,
                'daily_rental_rate' => 8.50,
                'purchase_price_estimate' => 3500.00,
                'maintenance_cost_per_year' => 180.00,
                'argentina_ws_code' => '20GP',
                'paraguay_ws_code' => '20GP',
                'customs_code' => '8609001000',
                'webservice_mapping' => json_encode(['type' => 'GP', 'size' => '20']),
                'allowed_conditions' => json_encode(['V', 'L', 'D']),
                'condition_descriptions' => 'V=Vacío, L=Lleno, D=Dañado',
                'compatible_vessel_types' => json_encode(['container_vessel', 'multipurpose']),
                'restricted_ports' => null,
                'handling_equipment_required' => json_encode(['spreader', 'crane']),
                'eco_friendly' => false,
                'carbon_footprint_kg' => 2500.00,
                'environmental_certifications' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'display_order' => 10,
                'icon' => 'fas fa-cube',
                'color_code' => '#4169E1',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // 2. CONTENEDOR 40GP
            [
                'code' => '40GP',
                'name' => 'Contenedor 40 pies General Purpose',
                'short_name' => '40GP',
                'description' => 'Contenedor estándar de 40 pies para carga general',
                'iso_code' => '42G1',
                'iso_size_type' => '42G1',
                'iso_group' => 'general',
                'length_feet' => '40',
                'width_feet' => '8',
                'height_feet' => '8.5',
                'length_mm' => 12192.00,
                'width_mm' => 2438.00,
                'height_mm' => 2591.00,
                'internal_length_mm' => 12032.00,
                'internal_width_mm' => 2352.00,
                'internal_height_mm' => 2393.00,
                'tare_weight_kg' => 3740.00,
                'max_gross_weight_kg' => 30480.00,
                'max_payload_kg' => 26740.00,
                'internal_volume_m3' => 67.70,
                'loading_volume_m3' => 66.80,
                'category' => 'dry_cargo',
                'is_refrigerated' => false,
                'is_heated' => false,
                'is_insulated' => false,
                'is_ventilated' => false,
                'has_electrical_supply' => false,
                'has_roof' => true,
                'has_sidewalls' => true,
                'has_end_walls' => true,
                'has_doors' => true,
                'has_removable_top' => false,
                'has_folding_sides' => false,
                'door_type' => 'standard',
                'door_width_mm' => 2340.00,
                'door_height_mm' => 2280.00,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'has_humidity_control' => false,
                'has_atmosphere_control' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_food' => true,
                'suitable_for_chemicals' => false,
                'suitable_for_liquids' => false,
                'suitable_for_bulk_cargo' => false,
                'suitable_for_heavy_cargo' => true,
                'suitable_for_oversized_cargo' => false,
                'requires_special_handling' => false,
                'requires_power_supply' => false,
                'requires_ventilation' => false,
                'requires_monitoring' => false,
                'stackable' => true,
                'max_stack_height' => 9,
                'csc_certified' => true,
                'food_grade' => true,
                'pharmaceutical_grade' => false,
                'certifications' => json_encode(['CSC', 'ISO']),
                'typical_lifespan_years' => 15,
                'inspection_interval_months' => 12,
                'requires_pretrip_inspection' => true,
                'requires_cleaning' => true,
                'requires_fumigation' => false,
                'daily_rental_rate' => 12.00,
                'purchase_price_estimate' => 4200.00,
                'maintenance_cost_per_year' => 220.00,
                'argentina_ws_code' => '40GP',
                'paraguay_ws_code' => '40GP',
                'customs_code' => '8609001000',
                'webservice_mapping' => json_encode(['type' => 'GP', 'size' => '40']),
                'allowed_conditions' => json_encode(['V', 'L', 'D']),
                'condition_descriptions' => 'V=Vacío, L=Lleno, D=Dañado',
                'compatible_vessel_types' => json_encode(['container_vessel', 'multipurpose']),
                'restricted_ports' => null,
                'handling_equipment_required' => json_encode(['spreader', 'crane']),
                'eco_friendly' => false,
                'carbon_footprint_kg' => 4200.00,
                'environmental_certifications' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'display_order' => 20,
                'icon' => 'fas fa-cube',
                'color_code' => '#4169E1',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // 3. CONTENEDOR 40HC
            [
                'code' => '40HC',
                'name' => 'Contenedor 40 pies High Cube',
                'short_name' => '40HC',
                'description' => 'Contenedor de 40 pies con altura extra',
                'iso_code' => '45G1',
                'iso_size_type' => '45G1',
                'iso_group' => 'high_cube',
                'length_feet' => '40',
                'width_feet' => '8',
                'height_feet' => '9.5',
                'length_mm' => 12192.00,
                'width_mm' => 2438.00,
                'height_mm' => 2896.00,
                'internal_length_mm' => 12032.00,
                'internal_width_mm' => 2352.00,
                'internal_height_mm' => 2698.00,
                'tare_weight_kg' => 3900.00,
                'max_gross_weight_kg' => 30480.00,
                'max_payload_kg' => 26580.00,
                'internal_volume_m3' => 76.30,
                'loading_volume_m3' => 75.20,
                'category' => 'dry_cargo',
                'is_refrigerated' => false,
                'is_heated' => false,
                'is_insulated' => false,
                'is_ventilated' => false,
                'has_electrical_supply' => false,
                'has_roof' => true,
                'has_sidewalls' => true,
                'has_end_walls' => true,
                'has_doors' => true,
                'has_removable_top' => false,
                'has_folding_sides' => false,
                'door_type' => 'standard',
                'door_width_mm' => 2340.00,
                'door_height_mm' => 2585.00,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'has_humidity_control' => false,
                'has_atmosphere_control' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_food' => true,
                'suitable_for_chemicals' => false,
                'suitable_for_liquids' => false,
                'suitable_for_bulk_cargo' => false,
                'suitable_for_heavy_cargo' => true,
                'suitable_for_oversized_cargo' => true,
                'requires_special_handling' => false,
                'requires_power_supply' => false,
                'requires_ventilation' => false,
                'requires_monitoring' => false,
                'stackable' => true,
                'max_stack_height' => 7,
                'csc_certified' => true,
                'food_grade' => true,
                'pharmaceutical_grade' => false,
                'certifications' => json_encode(['CSC', 'ISO']),
                'typical_lifespan_years' => 15,
                'inspection_interval_months' => 12,
                'requires_pretrip_inspection' => true,
                'requires_cleaning' => true,
                'requires_fumigation' => false,
                'daily_rental_rate' => 14.00,
                'purchase_price_estimate' => 4500.00,
                'maintenance_cost_per_year' => 240.00,
                'argentina_ws_code' => '40HC',
                'paraguay_ws_code' => '40HC',
                'customs_code' => '8609001000',
                'webservice_mapping' => json_encode(['type' => 'GP', 'size' => '40', 'height' => 'High']),
                'allowed_conditions' => json_encode(['V', 'L', 'D']),
                'condition_descriptions' => 'V=Vacío, L=Lleno, D=Dañado',
                'compatible_vessel_types' => json_encode(['container_vessel']),
                'restricted_ports' => json_encode(['Some height restrictions']),
                'handling_equipment_required' => json_encode(['high_spreader', 'crane']),
                'eco_friendly' => false,
                'carbon_footprint_kg' => 4500.00,
                'environmental_certifications' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'display_order' => 30,
                'icon' => 'fas fa-cube',
                'color_code' => '#FF6347',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // 4. CONTENEDOR REFRIGERADO 20RF
            [
                'code' => '20RF',
                'name' => 'Contenedor 20 pies Refrigerado',
                'short_name' => '20RF',
                'description' => 'Contenedor refrigerado de 20 pies para carga perecedera',
                'iso_code' => '22R1',
                'iso_size_type' => '22R1',
                'iso_group' => 'reefer',
                'length_feet' => '20',
                'width_feet' => '8',
                'height_feet' => '8.5',
                'length_mm' => 6058.00,
                'width_mm' => 2438.00,
                'height_mm' => 2591.00,
                'internal_length_mm' => 5444.00,
                'internal_width_mm' => 2268.00,
                'internal_height_mm' => 2250.00,
                'tare_weight_kg' => 3080.00,
                'max_gross_weight_kg' => 30480.00,
                'max_payload_kg' => 27400.00,
                'internal_volume_m3' => 27.80,
                'loading_volume_m3' => 26.50,
                'category' => 'refrigerated',
                'is_refrigerated' => true,
                'is_heated' => true,
                'is_insulated' => true,
                'is_ventilated' => true,
                'has_electrical_supply' => true,
                'has_roof' => true,
                'has_sidewalls' => true,
                'has_end_walls' => true,
                'has_doors' => true,
                'has_removable_top' => false,
                'has_folding_sides' => false,
                'door_type' => 'standard',
                'door_width_mm' => 2268.00,
                'door_height_mm' => 2250.00,
                'min_temperature_celsius' => -29.00,
                'max_temperature_celsius' => 25.00,
                'has_humidity_control' => true,
                'has_atmosphere_control' => true,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_food' => true,
                'suitable_for_chemicals' => false,
                'suitable_for_liquids' => false,
                'suitable_for_bulk_cargo' => false,
                'suitable_for_heavy_cargo' => true,
                'suitable_for_oversized_cargo' => false,
                'requires_special_handling' => true,
                'requires_power_supply' => true,
                'requires_ventilation' => false,
                'requires_monitoring' => true,
                'stackable' => true,
                'max_stack_height' => 9,
                'csc_certified' => true,
                'food_grade' => true,
                'pharmaceutical_grade' => true,
                'certifications' => json_encode(['CSC', 'HACCP', 'ATP']),
                'typical_lifespan_years' => 12,
                'inspection_interval_months' => 3,
                'requires_pretrip_inspection' => true,
                'requires_cleaning' => true,
                'requires_fumigation' => false,
                'daily_rental_rate' => 35.00,
                'purchase_price_estimate' => 45000.00,
                'maintenance_cost_per_year' => 1200.00,
                'argentina_ws_code' => '20RF',
                'paraguay_ws_code' => '20RF',
                'customs_code' => '8418500000',
                'webservice_mapping' => json_encode(['type' => 'RE', 'size' => '20', 'temperature' => 'controlled']),
                'allowed_conditions' => json_encode(['V', 'L']),
                'condition_descriptions' => 'V=Vacío con power, L=Lleno con temperature control',
                'compatible_vessel_types' => json_encode(['reefer_vessel', 'container_vessel_with_plugs']),
                'restricted_ports' => json_encode(['Ports without reefer facilities']),
                'handling_equipment_required' => json_encode(['reefer_spreader', 'power_connection']),
                'eco_friendly' => true,
                'carbon_footprint_kg' => 3200.00,
                'environmental_certifications' => json_encode(['Energy Star']),
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => true,
                'display_order' => 40,
                'icon' => 'fas fa-snowflake',
                'color_code' => '#00CED1',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // 5. CONTENEDOR OPEN TOP 20OT
            [
                'code' => '20OT',
                'name' => 'Contenedor 20 pies Open Top',
                'short_name' => '20OT',
                'description' => 'Contenedor de 20 pies con techo removible',
                'iso_code' => '22U1',
                'iso_size_type' => '22U1',
                'iso_group' => 'open_top',
                'length_feet' => '20',
                'width_feet' => '8',
                'height_feet' => '8.5',
                'length_mm' => 6058.00,
                'width_mm' => 2438.00,
                'height_mm' => 2591.00,
                'internal_length_mm' => 5898.00,
                'internal_width_mm' => 2352.00,
                'internal_height_mm' => 2370.00,
                'tare_weight_kg' => 2450.00,
                'max_gross_weight_kg' => 30480.00,
                'max_payload_kg' => 28030.00,
                'internal_volume_m3' => 32.90,
                'loading_volume_m3' => 32.00,
                'category' => 'open_top',
                'is_refrigerated' => false,
                'is_heated' => false,
                'is_insulated' => false,
                'is_ventilated' => true,
                'has_electrical_supply' => false,
                'has_roof' => false,
                'has_sidewalls' => true,
                'has_end_walls' => true,
                'has_doors' => true,
                'has_removable_top' => true,
                'has_folding_sides' => false,
                'door_type' => 'standard',
                'door_width_mm' => 2340.00,
                'door_height_mm' => 2280.00,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'has_humidity_control' => false,
                'has_atmosphere_control' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_food' => false,
                'suitable_for_chemicals' => false,
                'suitable_for_liquids' => false,
                'suitable_for_bulk_cargo' => false,
                'suitable_for_heavy_cargo' => true,
                'suitable_for_oversized_cargo' => true,
                'requires_special_handling' => true,
                'requires_power_supply' => false,
                'requires_ventilation' => false,
                'requires_monitoring' => false,
                'stackable' => true,
                'max_stack_height' => 7,
                'csc_certified' => true,
                'food_grade' => false,
                'pharmaceutical_grade' => false,
                'certifications' => json_encode(['CSC']),
                'typical_lifespan_years' => 15,
                'inspection_interval_months' => 12,
                'requires_pretrip_inspection' => true,
                'requires_cleaning' => true,
                'requires_fumigation' => false,
                'daily_rental_rate' => 15.00,
                'purchase_price_estimate' => 4000.00,
                'maintenance_cost_per_year' => 250.00,
                'argentina_ws_code' => '20OT',
                'paraguay_ws_code' => '20OT',
                'customs_code' => '8609001000',
                'webservice_mapping' => json_encode(['type' => 'UT', 'size' => '20', 'special' => 'open_top']),
                'allowed_conditions' => json_encode(['V', 'L', 'D']),
                'condition_descriptions' => 'V=Vacío con tarpaulin, L=Lleno, D=Dañado',
                'compatible_vessel_types' => json_encode(['container_vessel', 'multipurpose']),
                'restricted_ports' => json_encode(['Weather sensitive ports']),
                'handling_equipment_required' => json_encode(['crane', 'tarpaulin_system']),
                'eco_friendly' => false,
                'carbon_footprint_kg' => 2800.00,
                'environmental_certifications' => null,
                'active' => true,
                'is_standard' => false,
                'is_common' => false,
                'is_specialized' => true,
                'display_order' => 50,
                'icon' => 'fas fa-box-open',
                'color_code' => '#FF8C00',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],
        ];

        // Insertar todos los registros
        DB::table('container_types')->insert($containerTypes);

        $this->command->info('✅ Tipos de contenedor creados exitosamente');
        $this->command->info('📦 Total de tipos creados: ' . count($containerTypes));
        $this->command->line('');
        $this->command->line('Tipos creados:');
        foreach ($containerTypes as $type) {
            $this->command->line("  - {$type['code']}: {$type['name']}");
        }
    }
}