<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

/**
 * PackagingTypesSeeder - ACTUALIZADO CON DATOS DE tipo_embalaje.txt
 * 
 * MÓDULO 3: VIAJES Y CARGAS
 * Seeder para tipos de embalaje más comunes según estándares internacionales + datos nuevos
 * Compatible con códigos UN/ECE y webservices AR/PY
 * 
 * 100% coherente con migración create_packaging_types_table.php
 * 
 * DATOS AGREGADOS desde tipo_embalaje.txt:
 * A,A GRANEL - N,NO RETORNABLE - R,RETORNABLE - T,CONTENEDOR
 * (A, N, R ya existían, se agrega solo T)
 */
class PackagingTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $packagingTypes = [
            // === DATOS ORIGINALES DEL SISTEMA (mantener todos) ===
            
            // 1. PALLET ESTÁNDAR
            [
                'code' => 'PAL001',
                'name' => 'Pallet Estándar',
                'short_name' => 'Pallet',
                'description' => 'Plataforma de madera estándar para facilitar manejo y almacenamiento',
                'unece_code' => 'PAL',
                'iso_code' => 'PAL',
                'imdg_code' => null,
                'category' => 'pallet',
                'material_type' => 'wood',
                'length_mm' => 1200.00,
                'width_mm' => 1000.00,
                'height_mm' => 150.00,
                'diameter_mm' => null,
                'volume_liters' => null,
                'volume_m3' => 0.180,
                'empty_weight_kg' => 25.00,
                'max_gross_weight_kg' => 1500.00,
                'max_net_weight_kg' => 1475.00,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => true,
                'max_stack_height' => 10,
                'stacking_weight_limit_kg' => 15000.00,
                'is_reusable' => true,
                'is_returnable' => true,
                'is_collapsible' => false,
                'requires_palletizing' => false,
                'requires_strapping' => false,
                'requires_wrapping' => false,
                'requires_special_handling' => false,
                'handling_equipment' => 'forklift',
                'is_weatherproof' => false,
                'is_moisture_resistant' => false,
                'is_uv_resistant' => false,
                'min_temperature_celsius' => -40.00,
                'max_temperature_celsius' => 60.00,
                'requires_ventilation' => false,
                'requires_humidity_control' => false,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => false,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_fragile_items' => true,
                'suitable_for_heavy_items' => true,
                'suitable_for_bulk_cargo' => false,
                'provides_cushioning' => false,
                'provides_impact_protection' => false,
                'provides_theft_protection' => false,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => true,
                'is_biodegradable' => true,
                'is_compostable' => false,
                'contains_recycled_material' => false,
                'recycled_content_percent' => null,
                'disposal_instructions' => 'Reciclar en centros especializados en madera',
                'unit_cost' => 15.00,
                'cost_per_kg' => 0.60,
                'cost_per_m3' => 83.33,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 10,
                'fda_approved' => false,
                'food_contact_safe' => true,
                'pharmaceutical_grade' => false,
                'certifications' => json_encode(['ISPM-15']),
                'regulatory_compliance' => json_encode(['ISPM-15', 'NIMF-15']),
                'requires_labeling' => true,
                'allows_printing' => true,
                'requires_hazmat_marking' => false,
                'required_markings' => json_encode(['ISPM-15', 'País de origen']),
                'prohibited_markings' => null,
                'argentina_ws_code' => 'PAL',
                'paraguay_ws_code' => 'PAL',
                'customs_code' => '441010',
                'senasa_code' => null,
                'webservice_mapping' => json_encode(['type' => 'platform', 'material' => 'wood']),
                'industry_applications' => json_encode(['logistics', 'agriculture', 'manufacturing']),
                'commodity_compatibility' => json_encode(['general_cargo', 'agricultural_products']),
                'seasonal_considerations' => json_encode(['humidity_control_required']),
                'requires_testing' => false,
                'testing_frequency_days' => null,
                'quality_standards' => json_encode(['ISPM-15', 'EPAL']),
                'acceptable_defect_rate_percent' => 2.00,
                'widely_available' => true,
                'typical_lead_time_days' => 3,
                'preferred_suppliers' => json_encode(['Local wood suppliers']),
                'alternative_types' => json_encode(['Plastic pallets', 'Metal pallets']),
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'is_deprecated' => false,
                'display_order' => 10,
                'icon' => 'fas fa-pallet',
                'color_code' => '#8B4513',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // 2. CAJAS DE CARTÓN CORRUGADO
            [
                'code' => 'BOX001',
                'name' => 'Cajas de Cartón Corrugado',
                'short_name' => 'Cajas',
                'description' => 'Embalaje de cartón corrugado para mercadería general y alimentos',
                'unece_code' => 'BX',
                'iso_code' => '4G',
                'imdg_code' => null,
                'category' => 'box',
                'material_type' => 'cardboard',
                'length_mm' => 400.00,
                'width_mm' => 300.00,
                'height_mm' => 200.00,
                'diameter_mm' => null,
                'volume_liters' => 24.00,
                'volume_m3' => 0.024,
                'empty_weight_kg' => 0.50,
                'max_gross_weight_kg' => 25.00,
                'max_net_weight_kg' => 24.50,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => true,
                'max_stack_height' => 20,
                'stacking_weight_limit_kg' => 500.00,
                'is_reusable' => false,
                'is_returnable' => false,
                'is_collapsible' => true,
                'requires_palletizing' => true,
                'requires_strapping' => false,
                'requires_wrapping' => false,
                'requires_special_handling' => false,
                'handling_equipment' => 'manual',
                'is_weatherproof' => false,
                'is_moisture_resistant' => false,
                'is_uv_resistant' => false,
                'min_temperature_celsius' => -10.00,
                'max_temperature_celsius' => 50.00,
                'requires_ventilation' => true,
                'requires_humidity_control' => true,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => true,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_fragile_items' => true,
                'suitable_for_heavy_items' => false,
                'suitable_for_bulk_cargo' => false,
                'provides_cushioning' => true,
                'provides_impact_protection' => true,
                'provides_theft_protection' => false,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => true,
                'is_biodegradable' => true,
                'is_compostable' => true,
                'contains_recycled_material' => true,
                'recycled_content_percent' => 80.00,
                'disposal_instructions' => 'Reciclar en contenedores de papel y cartón',
                'unit_cost' => 2.50,
                'cost_per_kg' => 5.00,
                'cost_per_m3' => 104.17,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 100,
                'fda_approved' => true,
                'food_contact_safe' => true,
                'pharmaceutical_grade' => false,
                'certifications' => json_encode(['FDA', 'FSC']),
                'regulatory_compliance' => json_encode(['FDA', 'CE', 'MERCOSUR']),
                'requires_labeling' => true,
                'allows_printing' => true,
                'requires_hazmat_marking' => false,
                'required_markings' => json_encode(['Recycling symbol', 'Food safe']),
                'prohibited_markings' => json_encode(['Heavy metals inks']),
                'argentina_ws_code' => 'CX',
                'paraguay_ws_code' => 'CX',
                'customs_code' => '481910',
                'senasa_code' => 'CART001',
                'webservice_mapping' => json_encode(['type' => 'box', 'material' => 'cardboard']),
                'industry_applications' => json_encode(['food', 'pharmaceuticals', 'consumer_goods']),
                'commodity_compatibility' => json_encode(['dry_goods', 'packaged_food', 'electronics']),
                'seasonal_considerations' => json_encode(['avoid_high_humidity', 'protect_from_rain']),
                'requires_testing' => true,
                'testing_frequency_days' => 90,
                'quality_standards' => json_encode(['ISTA', 'TAPPI']),
                'acceptable_defect_rate_percent' => 1.00,
                'widely_available' => true,
                'typical_lead_time_days' => 7,
                'preferred_suppliers' => json_encode(['Corrugated manufacturers']),
                'alternative_types' => json_encode(['Plastic boxes', 'Wooden crates']),
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'is_deprecated' => false,
                'display_order' => 20,
                'icon' => 'fas fa-box',
                'color_code' => '#D2691E',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // === DATOS EXISTENTES DESDE SEEDERS ANTERIORES (A, N, R) ===

            // A,A GRANEL
            [
                'code' => 'A',
                'name' => 'A Granel',
                'short_name' => 'Granel',
                'description' => 'Mercadería transportada sin embalaje específico, a granel',
                'unece_code' => null,
                'iso_code' => null,
                'imdg_code' => null,
                'category' => 'bulk',
                'material_type' => 'other',
                'length_mm' => null,
                'width_mm' => null,
                'height_mm' => null,
                'diameter_mm' => null,
                'volume_liters' => null,
                'volume_m3' => null,
                'empty_weight_kg' => null,
                'max_gross_weight_kg' => null,
                'max_net_weight_kg' => null,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => true,
                'max_stack_height' => null,
                'stacking_weight_limit_kg' => null,
                'is_reusable' => false,
                'is_returnable' => false,
                'is_collapsible' => false,
                'requires_palletizing' => false,
                'requires_strapping' => false,
                'requires_wrapping' => false,
                'requires_special_handling' => true,
                'handling_equipment' => 'specialized',
                'is_weatherproof' => false,
                'is_moisture_resistant' => false,
                'is_uv_resistant' => false,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'requires_ventilation' => false,
                'requires_humidity_control' => false,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => false,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_fragile_items' => false,
                'suitable_for_heavy_items' => true,
                'suitable_for_bulk_cargo' => true,
                'provides_cushioning' => false,
                'provides_impact_protection' => false,
                'provides_theft_protection' => false,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => true,
                'is_biodegradable' => false,
                'is_compostable' => false,
                'contains_recycled_material' => false,
                'recycled_content_percent' => null,
                'disposal_instructions' => null,
                'unit_cost' => null,
                'cost_per_kg' => null,
                'cost_per_m3' => null,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 1,
                'fda_approved' => false,
                'food_contact_safe' => true,
                'pharmaceutical_grade' => false,
                'certifications' => null,
                'regulatory_compliance' => null,
                'requires_labeling' => true,
                'allows_printing' => true,
                'requires_hazmat_marking' => false,
                'required_markings' => null,
                'prohibited_markings' => null,
                'argentina_ws_code' => 'A',
                'paraguay_ws_code' => 'A',
                'customs_code' => null,
                'senasa_code' => null,
                'webservice_mapping' => json_encode(['type' => 'bulk', 'client_code' => 'A']),
                'industry_applications' => null,
                'commodity_compatibility' => null,
                'seasonal_considerations' => null,
                'requires_testing' => false,
                'testing_frequency_days' => null,
                'quality_standards' => null,
                'acceptable_defect_rate_percent' => 2.00,
                'widely_available' => true,
                'typical_lead_time_days' => null,
                'preferred_suppliers' => null,
                'alternative_types' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'is_deprecated' => false,
                'display_order' => 100,
                'icon' => 'fas fa-mountain',
                'color_code' => '#8B4513',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // N,NO RETORNABLE
            [
                'code' => 'N',
                'name' => 'No Retornable',
                'short_name' => 'No Retornable',
                'description' => 'Embalaje de un solo uso, no retornable',
                'unece_code' => null,
                'iso_code' => null,
                'imdg_code' => null,
                'category' => 'box',
                'material_type' => 'cardboard',
                'length_mm' => null,
                'width_mm' => null,
                'height_mm' => null,
                'diameter_mm' => null,
                'volume_liters' => null,
                'volume_m3' => null,
                'empty_weight_kg' => null,
                'max_gross_weight_kg' => null,
                'max_net_weight_kg' => null,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => true,
                'max_stack_height' => null,
                'stacking_weight_limit_kg' => null,
                'is_reusable' => false,
                'is_returnable' => false,
                'is_collapsible' => false,
                'requires_palletizing' => false,
                'requires_strapping' => false,
                'requires_wrapping' => false,
                'requires_special_handling' => false,
                'handling_equipment' => 'manual',
                'is_weatherproof' => false,
                'is_moisture_resistant' => false,
                'is_uv_resistant' => false,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'requires_ventilation' => false,
                'requires_humidity_control' => false,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => false,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_fragile_items' => false,
                'suitable_for_heavy_items' => true,
                'suitable_for_bulk_cargo' => false,
                'provides_cushioning' => false,
                'provides_impact_protection' => false,
                'provides_theft_protection' => false,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => true,
                'is_biodegradable' => false,
                'is_compostable' => false,
                'contains_recycled_material' => false,
                'recycled_content_percent' => null,
                'disposal_instructions' => null,
                'unit_cost' => null,
                'cost_per_kg' => null,
                'cost_per_m3' => null,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 1,
                'fda_approved' => false,
                'food_contact_safe' => true,
                'pharmaceutical_grade' => false,
                'certifications' => null,
                'regulatory_compliance' => null,
                'requires_labeling' => true,
                'allows_printing' => true,
                'requires_hazmat_marking' => false,
                'required_markings' => null,
                'prohibited_markings' => null,
                'argentina_ws_code' => 'N',
                'paraguay_ws_code' => 'N',
                'customs_code' => null,
                'senasa_code' => null,
                'webservice_mapping' => json_encode(['type' => 'non_returnable', 'client_code' => 'N']),
                'industry_applications' => null,
                'commodity_compatibility' => null,
                'seasonal_considerations' => null,
                'requires_testing' => false,
                'testing_frequency_days' => null,
                'quality_standards' => null,
                'acceptable_defect_rate_percent' => 2.00,
                'widely_available' => true,
                'typical_lead_time_days' => null,
                'preferred_suppliers' => null,
                'alternative_types' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'is_deprecated' => false,
                'display_order' => 200,
                'icon' => 'fas fa-box-open',
                'color_code' => '#D2691E',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // R,RETORNABLE
            [
                'code' => 'R',
                'name' => 'Retornable',
                'short_name' => 'Retornable',
                'description' => 'Embalaje reutilizable y retornable',
                'unece_code' => null,
                'iso_code' => null,
                'imdg_code' => null,
                'category' => 'container',
                'material_type' => 'plastic',
                'length_mm' => null,
                'width_mm' => null,
                'height_mm' => null,
                'diameter_mm' => null,
                'volume_liters' => null,
                'volume_m3' => null,
                'empty_weight_kg' => null,
                'max_gross_weight_kg' => null,
                'max_net_weight_kg' => null,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => true,
                'max_stack_height' => null,
                'stacking_weight_limit_kg' => null,
                'is_reusable' => true,
                'is_returnable' => true,
                'is_collapsible' => false,
                'requires_palletizing' => false,
                'requires_strapping' => false,
                'requires_wrapping' => false,
                'requires_special_handling' => false,
                'handling_equipment' => 'manual',
                'is_weatherproof' => false,
                'is_moisture_resistant' => false,
                'is_uv_resistant' => false,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'requires_ventilation' => false,
                'requires_humidity_control' => false,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => false,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_fragile_items' => false,
                'suitable_for_heavy_items' => true,
                'suitable_for_bulk_cargo' => false,
                'provides_cushioning' => false,
                'provides_impact_protection' => false,
                'provides_theft_protection' => false,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => true,
                'is_biodegradable' => false,
                'is_compostable' => false,
                'contains_recycled_material' => false,
                'recycled_content_percent' => null,
                'disposal_instructions' => null,
                'unit_cost' => null,
                'cost_per_kg' => null,
                'cost_per_m3' => null,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 1,
                'fda_approved' => false,
                'food_contact_safe' => true,
                'pharmaceutical_grade' => false,
                'certifications' => null,
                'regulatory_compliance' => null,
                'requires_labeling' => true,
                'allows_printing' => true,
                'requires_hazmat_marking' => false,
                'required_markings' => null,
                'prohibited_markings' => null,
                'argentina_ws_code' => 'R',
                'paraguay_ws_code' => 'R',
                'customs_code' => null,
                'senasa_code' => null,
                'webservice_mapping' => json_encode(['type' => 'returnable', 'client_code' => 'R']),
                'industry_applications' => null,
                'commodity_compatibility' => null,
                'seasonal_considerations' => null,
                'requires_testing' => false,
                'testing_frequency_days' => null,
                'quality_standards' => null,
                'acceptable_defect_rate_percent' => 2.00,
                'widely_available' => true,
                'typical_lead_time_days' => null,
                'preferred_suppliers' => null,
                'alternative_types' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'is_deprecated' => false,
                'display_order' => 300,
                'icon' => 'fas fa-recycle',
                'color_code' => '#32CD32',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // === NUEVO DATO DESDE tipo_embalaje.txt ===

            // T,CONTENEDOR
            [
                'code' => 'T',
                'name' => 'CONTENEDOR',
                'short_name' => 'Contenedor',
                'description' => 'Embalaje en contenedores ISO estándar',
                'unece_code' => null,
                'iso_code' => null,
                'imdg_code' => null,
                'category' => 'container',
                'material_type' => 'metal',
                'length_mm' => null,
                'width_mm' => null,
                'height_mm' => null,
                'diameter_mm' => null,
                'volume_liters' => null,
                'volume_m3' => null,
                'empty_weight_kg' => null,
                'max_gross_weight_kg' => null,
                'max_net_weight_kg' => null,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => true,
                'max_stack_height' => null,
                'stacking_weight_limit_kg' => null,
                'is_reusable' => true,
                'is_returnable' => true,
                'is_collapsible' => false,
                'requires_palletizing' => false,
                'requires_strapping' => false,
                'requires_wrapping' => false,
                'requires_special_handling' => false,
                'handling_equipment' => 'forklift',
                'is_weatherproof' => true,
                'is_moisture_resistant' => true,
                'is_uv_resistant' => true,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'requires_ventilation' => false,
                'requires_humidity_control' => false,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => false,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_fragile_items' => false,
                'suitable_for_heavy_items' => true,
                'suitable_for_bulk_cargo' => false,
                'provides_cushioning' => false,
                'provides_impact_protection' => true,
                'provides_theft_protection' => true,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => true,
                'is_biodegradable' => false,
                'is_compostable' => false,
                'contains_recycled_material' => false,
                'recycled_content_percent' => null,
                'disposal_instructions' => null,
                'unit_cost' => null,
                'cost_per_kg' => null,
                'cost_per_m3' => null,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 1,
                'fda_approved' => false,
                'food_contact_safe' => true,
                'pharmaceutical_grade' => false,
                'certifications' => null,
                'regulatory_compliance' => null,
                'requires_labeling' => true,
                'allows_printing' => true,
                'requires_hazmat_marking' => false,
                'required_markings' => null,
                'prohibited_markings' => null,
                'argentina_ws_code' => 'T',
                'paraguay_ws_code' => 'T',
                'customs_code' => null,
                'senasa_code' => null,
                'webservice_mapping' => json_encode(['type' => 'container', 'client_code' => 'T']),
                'industry_applications' => null,
                'commodity_compatibility' => null,
                'seasonal_considerations' => null,
                'requires_testing' => false,
                'testing_frequency_days' => null,
                'quality_standards' => null,
                'acceptable_defect_rate_percent' => 2.00,
                'widely_available' => true,
                'typical_lead_time_days' => null,
                'preferred_suppliers' => null,
                'alternative_types' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'is_deprecated' => false,
                'display_order' => 400,
                'icon' => 'fas fa-shipping-fast',
                'color_code' => '#4169E1',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],
        ];

        // Insertar todos los registros
        DB::table('packaging_types')->insert($packagingTypes);

        $this->command->info('✅ Tipos de embalaje creados exitosamente');
        $this->command->info('📦 Total de tipos creados: ' . count($packagingTypes));
        $this->command->line('');
        $this->command->line('Tipos creados:');
        foreach ($packagingTypes as $type) {
            $this->command->line("  - {$type['code']}: {$type['name']}");
        }
    }
}