<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

/**
 * PackagingTypesSeeder - CORREGIDO CON DATOS DE tipo_embalaje.txt
 * 
 * MÓDULO 3: VIAJES Y CARGAS
 * Seeder para tipos de embalaje usando datos exactos de tipo_embalaje.txt
 * 100% coherente con migración create_packaging_types_table.php
 * 
 * CORRECCIÓN: Solo campos obligatorios y datos exactos
 * DATOS EXACTOS desde tipo_embalaje.txt:
 * - A,A GRANEL
 * - N,NO RETORNABLE
 * - R,RETORNABLE  
 * - T,CONTENEDOR
 */
class PackagingTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $packagingTypes = [
            // A,A GRANEL
            [
                'code' => 'A',
                'name' => 'A GRANEL',
                'short_name' => 'Granel',
                'description' => 'Mercadería transportada sin embalaje específico, a granel',
                'unece_code' => null,
                'iso_code' => null,
                'imdg_code' => null,
                'category' => 'bulk',
                'material_type' => 'other',
                'length_mm' => null,
                'width_mm' => null,
                'height_mm' => null,
                'diameter_mm' => null,
                'volume_liters' => null,
                'volume_m3' => null,
                'empty_weight_kg' => null,
                'max_gross_weight_kg' => null,
                'max_net_weight_kg' => null,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => false,
                'max_stack_height' => null,
                'stacking_weight_limit_kg' => null,
                'is_reusable' => false,
                'is_returnable' => false,
                'is_collapsible' => false,
                'requires_palletizing' => false,
                'requires_strapping' => false,
                'requires_wrapping' => false,
                'requires_special_handling' => true,
                'handling_equipment' => 'specialized',
                'is_weatherproof' => false,
                'is_moisture_resistant' => false,
                'is_uv_resistant' => false,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'requires_ventilation' => false,
                'requires_humidity_control' => false,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => true,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_fragile_items' => false,
                'suitable_for_heavy_items' => true,
                'suitable_for_bulk_cargo' => true,
                'provides_cushioning' => false,
                'provides_impact_protection' => false,
                'provides_theft_protection' => false,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => false,
                'is_biodegradable' => false,
                'is_compostable' => false,
                'contains_recycled_material' => false,
                'recycled_content_percent' => null,
                'disposal_instructions' => null,
                'unit_cost' => null,
                'cost_per_kg' => null,
                'cost_per_m3' => null,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 1,
                'fda_approved' => false,
                'food_contact_safe' => false,
                'pharmaceutical_grade' => false,
                'certifications' => null,
                'regulatory_compliance' => null,
                'requires_labeling' => false,
                'allows_printing' => false,
                'requires_hazmat_marking' => false,
                'required_markings' => null,
                'prohibited_markings' => null,
                'argentina_ws_code' => 'A',
                'paraguay_ws_code' => 'A',
                'customs_code' => null,
                'senasa_code' => null,
                'webservice_mapping' => json_encode(['type' => 'bulk', 'client_code' => 'A']),
                'industry_applications' => null,
                'commodity_compatibility' => null,
                'seasonal_considerations' => null,
                'requires_testing' => false,
                'testing_frequency_days' => null,
                'quality_standards' => null,
                'acceptable_defect_rate_percent' => 5.00,
                'widely_available' => true,
                'typical_lead_time_days' => null,
                'preferred_suppliers' => null,
                'alternative_types' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => true,
                'is_deprecated' => false,
                'display_order' => 100,
                'icon' => 'fas fa-mountain',
                'color_code' => '#8B4513',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // N,NO RETORNABLE
            [
                'code' => 'N',
                'name' => 'NO RETORNABLE',
                'short_name' => 'No Retornable',
                'description' => 'Embalaje de un solo uso, no reutilizable ni retornable',
                'unece_code' => null,
                'iso_code' => null,
                'imdg_code' => null,
                'category' => 'box',
                'material_type' => 'cardboard',
                'length_mm' => null,
                'width_mm' => null,
                'height_mm' => null,
                'diameter_mm' => null,
                'volume_liters' => null,
                'volume_m3' => null,
                'empty_weight_kg' => null,
                'max_gross_weight_kg' => null,
                'max_net_weight_kg' => null,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => true,
                'max_stack_height' => null,
                'stacking_weight_limit_kg' => null,
                'is_reusable' => false,
                'is_returnable' => false,
                'is_collapsible' => false,
                'requires_palletizing' => false,
                'requires_strapping' => false,
                'requires_wrapping' => false,
                'requires_special_handling' => false,
                'handling_equipment' => 'manual',
                'is_weatherproof' => false,
                'is_moisture_resistant' => false,
                'is_uv_resistant' => false,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'requires_ventilation' => false,
                'requires_humidity_control' => false,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => false,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_fragile_items' => false,
                'suitable_for_heavy_items' => true,
                'suitable_for_bulk_cargo' => false,
                'provides_cushioning' => false,
                'provides_impact_protection' => false,
                'provides_theft_protection' => false,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => true,
                'is_biodegradable' => false,
                'is_compostable' => false,
                'contains_recycled_material' => false,
                'recycled_content_percent' => null,
                'disposal_instructions' => null,
                'unit_cost' => null,
                'cost_per_kg' => null,
                'cost_per_m3' => null,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 1,
                'fda_approved' => false,
                'food_contact_safe' => true,
                'pharmaceutical_grade' => false,
                'certifications' => null,
                'regulatory_compliance' => null,
                'requires_labeling' => true,
                'allows_printing' => true,
                'requires_hazmat_marking' => false,
                'required_markings' => null,
                'prohibited_markings' => null,
                'argentina_ws_code' => 'N',
                'paraguay_ws_code' => 'N',
                'customs_code' => null,
                'senasa_code' => null,
                'webservice_mapping' => json_encode(['type' => 'non_returnable', 'client_code' => 'N']),
                'industry_applications' => null,
                'commodity_compatibility' => null,
                'seasonal_considerations' => null,
                'requires_testing' => false,
                'testing_frequency_days' => null,
                'quality_standards' => null,
                'acceptable_defect_rate_percent' => 2.00,
                'widely_available' => true,
                'typical_lead_time_days' => null,
                'preferred_suppliers' => null,
                'alternative_types' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'is_deprecated' => false,
                'display_order' => 200,
                'icon' => 'fas fa-box-open',
                'color_code' => '#D2691E',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // R,RETORNABLE
            [
                'code' => 'R',
                'name' => 'RETORNABLE',
                'short_name' => 'Retornable',
                'description' => 'Embalaje reutilizable y retornable',
                'unece_code' => null,
                'iso_code' => null,
                'imdg_code' => null,
                'category' => 'container',
                'material_type' => 'plastic',
                'length_mm' => null,
                'width_mm' => null,
                'height_mm' => null,
                'diameter_mm' => null,
                'volume_liters' => null,
                'volume_m3' => null,
                'empty_weight_kg' => null,
                'max_gross_weight_kg' => null,
                'max_net_weight_kg' => null,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => true,
                'max_stack_height' => null,
                'stacking_weight_limit_kg' => null,
                'is_reusable' => true,
                'is_returnable' => true,
                'is_collapsible' => false,
                'requires_palletizing' => false,
                'requires_strapping' => false,
                'requires_wrapping' => false,
                'requires_special_handling' => false,
                'handling_equipment' => 'manual',
                'is_weatherproof' => false,
                'is_moisture_resistant' => false,
                'is_uv_resistant' => false,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'requires_ventilation' => false,
                'requires_humidity_control' => false,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => false,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => false,
                'suitable_for_fragile_items' => false,
                'suitable_for_heavy_items' => true,
                'suitable_for_bulk_cargo' => false,
                'provides_cushioning' => false,
                'provides_impact_protection' => false,
                'provides_theft_protection' => false,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => true,
                'is_biodegradable' => false,
                'is_compostable' => false,
                'contains_recycled_material' => false,
                'recycled_content_percent' => null,
                'disposal_instructions' => null,
                'unit_cost' => null,
                'cost_per_kg' => null,
                'cost_per_m3' => null,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 1,
                'fda_approved' => false,
                'food_contact_safe' => true,
                'pharmaceutical_grade' => false,
                'certifications' => null,
                'regulatory_compliance' => null,
                'requires_labeling' => true,
                'allows_printing' => true,
                'requires_hazmat_marking' => false,
                'required_markings' => null,
                'prohibited_markings' => null,
                'argentina_ws_code' => 'R',
                'paraguay_ws_code' => 'R',
                'customs_code' => null,
                'senasa_code' => null,
                'webservice_mapping' => json_encode(['type' => 'returnable', 'client_code' => 'R']),
                'industry_applications' => null,
                'commodity_compatibility' => null,
                'seasonal_considerations' => null,
                'requires_testing' => false,
                'testing_frequency_days' => null,
                'quality_standards' => null,
                'acceptable_defect_rate_percent' => 2.00,
                'widely_available' => true,
                'typical_lead_time_days' => null,
                'preferred_suppliers' => null,
                'alternative_types' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'is_deprecated' => false,
                'display_order' => 300,
                'icon' => 'fas fa-recycle',
                'color_code' => '#228B22',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],

            // T,CONTENEDOR
            [
                'code' => 'T',
                'name' => 'CONTENEDOR',
                'short_name' => 'Contenedor',
                'description' => 'Embalaje en contenedor estándar',
                'unece_code' => null,
                'iso_code' => null,
                'imdg_code' => null,
                'category' => 'container',
                'material_type' => 'metal',
                'length_mm' => null,
                'width_mm' => null,
                'height_mm' => null,
                'diameter_mm' => null,
                'volume_liters' => null,
                'volume_m3' => null,
                'empty_weight_kg' => null,
                'max_gross_weight_kg' => null,
                'max_net_weight_kg' => null,
                'weight_tolerance_percent' => 5.00,
                'is_stackable' => true,
                'max_stack_height' => null,
                'stacking_weight_limit_kg' => null,
                'is_reusable' => true,
                'is_returnable' => true,
                'is_collapsible' => false,
                'requires_palletizing' => false,
                'requires_strapping' => true,
                'requires_wrapping' => false,
                'requires_special_handling' => true,
                'handling_equipment' => 'crane',
                'is_weatherproof' => true,
                'is_moisture_resistant' => true,
                'is_uv_resistant' => true,
                'min_temperature_celsius' => null,
                'max_temperature_celsius' => null,
                'requires_ventilation' => false,
                'requires_humidity_control' => false,
                'suitable_for_food' => true,
                'suitable_for_liquids' => false,
                'suitable_for_powders' => false,
                'suitable_for_chemicals' => false,
                'suitable_for_dangerous_goods' => true,
                'suitable_for_fragile_items' => true,
                'suitable_for_heavy_items' => true,
                'suitable_for_bulk_cargo' => false,
                'provides_cushioning' => false,
                'provides_impact_protection' => true,
                'provides_theft_protection' => true,
                'is_tamper_evident' => false,
                'is_child_resistant' => false,
                'is_hermetic' => false,
                'is_recyclable' => true,
                'is_biodegradable' => false,
                'is_compostable' => false,
                'contains_recycled_material' => false,
                'recycled_content_percent' => null,
                'disposal_instructions' => null,
                'unit_cost' => null,
                'cost_per_kg' => null,
                'cost_per_m3' => null,
                'cost_varies_by_quantity' => true,
                'minimum_order_quantity' => 1,
                'fda_approved' => false,
                'food_contact_safe' => true,
                'pharmaceutical_grade' => false,
                'certifications' => null,
                'regulatory_compliance' => null,
                'requires_labeling' => true,
                'allows_printing' => true,
                'requires_hazmat_marking' => false,
                'required_markings' => null,
                'prohibited_markings' => null,
                'argentina_ws_code' => 'T',
                'paraguay_ws_code' => 'T',
                'customs_code' => null,
                'senasa_code' => null,
                'webservice_mapping' => json_encode(['type' => 'container', 'client_code' => 'T']),
                'industry_applications' => null,
                'commodity_compatibility' => null,
                'seasonal_considerations' => null,
                'requires_testing' => false,
                'testing_frequency_days' => null,
                'quality_standards' => null,
                'acceptable_defect_rate_percent' => 2.00,
                'widely_available' => true,
                'typical_lead_time_days' => null,
                'preferred_suppliers' => null,
                'alternative_types' => null,
                'active' => true,
                'is_standard' => true,
                'is_common' => true,
                'is_specialized' => false,
                'is_deprecated' => false,
                'display_order' => 400,
                'icon' => 'fas fa-shipping-fast',
                'color_code' => '#4169E1',
                'created_date' => $now,
                'created_by_user_id' => null,
            ],
        ];

        // Insertar todos los registros
        DB::table('packaging_types')->insert($packagingTypes);

        $this->command->info('✅ Tipos de embalaje creados exitosamente');
        $this->command->info('📦 Total de tipos creados: ' . count($packagingTypes));
        $this->command->line('');
        $this->command->line('Tipos creados desde tipo_embalaje.txt:');
        foreach ($packagingTypes as $type) {
            $this->command->line("  - {$type['code']}: {$type['name']}");
        }
    }
}