<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VesselTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Seed para tipos de embarcación del sistema de cargas fluviales y marítimas
     * Incluye barcazas, remolcadores, autopropulsados, empujadores y mixtos
     */
    public function run(): void
    {
        $this->command->info('🚢 Creando tipos de embarcación...');

        // Verificar si ya existen tipos de embarcación
        $existingCount = DB::table('vessel_types')->count();
        
        if ($existingCount > 0) {
            $this->command->warn("⚠️  Ya existen {$existingCount} tipos de embarcación.");
            $this->command->info('Saltando creación para evitar duplicados...');
            return;
        }

        $vesselTypes = $this->getVesselTypesData();

        foreach ($vesselTypes as $type) {
            DB::table('vessel_types')->insert(array_merge($type, [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'created_date' => Carbon::now(),
            ]));
        }

        $this->command->info('✅ ' . count($vesselTypes) . ' tipos de embarcación creados exitosamente');
        
        // Mostrar estadísticas
        $stats = [
            'barge' => collect($vesselTypes)->where('category', 'barge')->count(),
            'tugboat' => collect($vesselTypes)->where('category', 'tugboat')->count(),
            'self_propelled' => collect($vesselTypes)->where('category', 'self_propelled')->count(),
            'pusher' => collect($vesselTypes)->where('category', 'pusher')->count(),
            'mixed' => collect($vesselTypes)->where('category', 'mixed')->count(),
        ];

        $this->command->table(
            ['Categoría', 'Cantidad'],
            [
                ['Barcazas', $stats['barge']],
                ['Remolcadores', $stats['tugboat']],
                ['Autopropulsados', $stats['self_propelled']],
                ['Empujadores', $stats['pusher']],
                ['Mixtos', $stats['mixed']],
            ]
        );
    }

    /**
     * Obtener datos de tipos de embarcación.
     */
    private function getVesselTypesData(): array
    {
        return [
            // ========== BARCAZAS ==========
            [
                'code' => 'BARGE_STD_001',
                'name' => 'Barcaza Estándar de Contenedores',
                'short_name' => 'Barcaza Contenedores',
                'description' => 'Barcaza estándar diseñada específicamente para transporte de contenedores de 20\' y 40\'. Ideal para rutas fluviales principales.',
                'category' => 'barge',
                'propulsion_type' => 'pushed',
                'min_length' => 80.0,
                'max_length' => 120.0,
                'min_beam' => 12.0,
                'max_beam' => 18.0,
                'min_draft' => 2.5,
                'max_draft' => 4.0,
                'min_deadweight' => 800.0,
                'max_deadweight' => 1500.0,
                'handles_containers' => true,
                'handles_bulk_cargo' => false,
                'handles_liquid_cargo' => false,
                'handles_general_cargo' => true,
                'handles_dangerous_goods' => true,
                'handles_passengers' => false,
                'river_navigation' => true,
                'maritime_navigation' => true,
                'can_be_lead_vessel' => false,
                'can_be_in_convoy' => true,
                'max_convoy_size' => 6,
                'crew_capacity' => 0,
                'passenger_capacity' => 0,
                'fuel_capacity_liters' => 0.0,
                'engine_configuration' => null,
                'max_speed_knots' => 0.0,
                'service_speed_knots' => 0.0,
                'construction_materials' => 'Acero naval, recubrimiento anticorrosivo',
                'typical_lifespan_years' => 25,
                'environmental_standards' => 'IMO MARPOL, certificación verde',
                'regulatory_requirements' => 'Inspección anual, certificado de navegabilidad',
                'maintenance_interval_months' => 6,
                'requires_dry_dock' => true,
                'dry_dock_interval_months' => 24,
                'active' => true,
                'is_common' => true,
                'is_specialized' => false,
                'display_order' => 10,
                'icon' => 'ship-container',
                'color_code' => '#3B82F6',
            ],
            [
                'code' => 'BARGE_BULK_001',
                'name' => 'Barcaza de Carga a Granel',
                'short_name' => 'Barcaza Granel',
                'description' => 'Barcaza especializada en transporte de granos, minerales y otros productos a granel. Equipada con sistema de descarga neumática.',
                'category' => 'barge',
                'propulsion_type' => 'pushed',
                'min_length' => 90.0,
                'max_length' => 140.0,
                'min_beam' => 15.0,
                'max_beam' => 22.0,
                'min_draft' => 3.0,
                'max_draft' => 5.0,
                'min_deadweight' => 1200.0,
                'max_deadweight' => 2500.0,
                'handles_containers' => false,
                'handles_bulk_cargo' => true,
                'handles_liquid_cargo' => false,
                'handles_general_cargo' => false,
                'handles_dangerous_goods' => false,
                'handles_passengers' => false,
                'river_navigation' => true,
                'maritime_navigation' => true,
                'can_be_lead_vessel' => false,
                'can_be_in_convoy' => true,
                'max_convoy_size' => 4,
                'crew_capacity' => 0,
                'passenger_capacity' => 0,
                'fuel_capacity_liters' => 0.0,
                'engine_configuration' => null,
                'max_speed_knots' => 0.0,
                'service_speed_knots' => 0.0,
                'construction_materials' => 'Acero naval reforzado, bodegas selladas',
                'typical_lifespan_years' => 30,
                'environmental_standards' => 'Certificación ambiental para granos',
                'regulatory_requirements' => 'Inspección sanitaria trimestral',
                'maintenance_interval_months' => 4,
                'requires_dry_dock' => true,
                'dry_dock_interval_months' => 18,
                'active' => true,
                'is_common' => true,
                'is_specialized' => true,
                'display_order' => 20,
                'icon' => 'ship-bulk',
                'color_code' => '#059669',
            ],
            [
                'code' => 'BARGE_TANK_001',
                'name' => 'Barcaza Tanque para Líquidos',
                'short_name' => 'Barcaza Tanque',
                'description' => 'Barcaza especializada para transporte de combustibles, aceites y productos químicos líquidos. Cumple estándares internacionales de seguridad.',
                'category' => 'barge',
                'propulsion_type' => 'pushed',
                'min_length' => 70.0,
                'max_length' => 110.0,
                'min_beam' => 11.0,
                'max_beam' => 16.0,
                'min_draft' => 2.0,
                'max_draft' => 3.5,
                'min_deadweight' => 600.0,
                'max_deadweight' => 1200.0,
                'handles_containers' => false,
                'handles_bulk_cargo' => false,
                'handles_liquid_cargo' => true,
                'handles_general_cargo' => false,
                'handles_dangerous_goods' => true,
                'handles_passengers' => false,
                'river_navigation' => true,
                'maritime_navigation' => true,
                'can_be_lead_vessel' => false,
                'can_be_in_convoy' => true,
                'max_convoy_size' => 3,
                'crew_capacity' => 0,
                'passenger_capacity' => 0,
                'fuel_capacity_liters' => 0.0,
                'engine_configuration' => null,
                'max_speed_knots' => 0.0,
                'service_speed_knots' => 0.0,
                'construction_materials' => 'Acero inoxidable, doble casco',
                'typical_lifespan_years' => 20,
                'environmental_standards' => 'IMO tanker standards, certificación SOLAS',
                'regulatory_requirements' => 'Inspección mensual, certificado ISGOTT',
                'maintenance_interval_months' => 3,
                'requires_dry_dock' => true,
                'dry_dock_interval_months' => 12,
                'active' => true,
                'is_common' => false,
                'is_specialized' => true,
                'display_order' => 30,
                'icon' => 'ship-tank',
                'color_code' => '#DC2626',
            ],
            [
                'code' => 'BARGE_MULTI_001',
                'name' => 'Barcaza Multipropósito',
                'short_name' => 'Barcaza Multi',
                'description' => 'Barcaza versátil diseñada para transportar diferentes tipos de carga. Ideal para rutas con carga mixta y operaciones flexibles.',
                'category' => 'barge',
                'propulsion_type' => 'pushed',
                'min_length' => 75.0,
                'max_length' => 115.0,
                'min_beam' => 13.0,
                'max_beam' => 17.0,
                'min_draft' => 2.5,
                'max_draft' => 4.0,
                'min_deadweight' => 700.0,
                'max_deadweight' => 1300.0,
                'handles_containers' => true,
                'handles_bulk_cargo' => true,
                'handles_liquid_cargo' => false,
                'handles_general_cargo' => true,
                'handles_dangerous_goods' => false,
                'handles_passengers' => false,
                'river_navigation' => true,
                'maritime_navigation' => true,
                'can_be_lead_vessel' => false,
                'can_be_in_convoy' => true,
                'max_convoy_size' => 5,
                'crew_capacity' => 0,
                'passenger_capacity' => 0,
                'fuel_capacity_liters' => 0.0,
                'engine_configuration' => null,
                'max_speed_knots' => 0.0,
                'service_speed_knots' => 0.0,
                'construction_materials' => 'Acero naval, cubierta adaptable',
                'typical_lifespan_years' => 28,
                'environmental_standards' => 'Certificación estándar',
                'regulatory_requirements' => 'Inspección semestral',
                'maintenance_interval_months' => 6,
                'requires_dry_dock' => true,
                'dry_dock_interval_months' => 24,
                'active' => true,
                'is_common' => true,
                'is_specialized' => false,
                'display_order' => 40,
                'icon' => 'ship-multi',
                'color_code' => '#7C3AED',
            ],

            // ========== REMOLCADORES ==========
            [
                'code' => 'TUG_HARBOR_001',
                'name' => 'Remolcador de Puerto',
                'short_name' => 'Remolcador Puerto',
                'description' => 'Remolcador potente diseñado para maniobras en puerto y asistencia a embarcaciones grandes. Alta maniobrabilidad en espacios reducidos.',
                'category' => 'tugboat',
                'propulsion_type' => 'self_propelled',
                'min_length' => 25.0,
                'max_length' => 40.0,
                'min_beam' => 8.0,
                'max_beam' => 12.0,
                'min_draft' => 3.0,
                'max_draft' => 5.0,
                'min_deadweight' => 50.0,
                'max_deadweight' => 150.0,
                'handles_containers' => false,
                'handles_bulk_cargo' => false,
                'handles_liquid_cargo' => false,
                'handles_general_cargo' => false,
                'handles_dangerous_goods' => false,
                'handles_passengers' => true,
                'river_navigation' => true,
                'maritime_navigation' => true,
                'can_be_lead_vessel' => true,
                'can_be_in_convoy' => true,
                'max_convoy_size' => 3,
                'crew_capacity' => 8,
                'passenger_capacity' => 2,
                'fuel_capacity_liters' => 15000.0,
                'engine_configuration' => 'Twin diesel engines, 2000-3500 HP',
                'max_speed_knots' => 14.0,
                'service_speed_knots' => 10.0,
                'construction_materials' => 'Acero naval reforzado, protección de hélices',
                'typical_lifespan_years' => 30,
                'environmental_standards' => 'IMO Tier III emissions',
                'regulatory_requirements' => 'Certificado de potencia, inspección trimestral',
                'maintenance_interval_months' => 4,
                'requires_dry_dock' => true,
                'dry_dock_interval_months' => 18,
                'active' => true,
                'is_common' => true,
                'is_specialized' => true,
                'display_order' => 50,
                'icon' => 'ship-tugboat',
                'color_code' => '#EF4444',
            ],
            [
                'code' => 'TUG_RIVER_001',
                'name' => 'Remolcador Fluvial',
                'short_name' => 'Remolcador Fluvial',
                'description' => 'Remolcador especializado para navegación fluvial. Diseño optimizado para aguas poco profundas y corrientes fuertes.',
                'category' => 'tugboat',
                'propulsion_type' => 'self_propelled',
                'min_length' => 30.0,
                'max_length' => 45.0,
                'min_beam' => 9.0,
                'max_beam' => 13.0,
                'min_draft' => 2.5,
                'max_draft' => 4.0,
                'min_deadweight' => 80.0,
                'max_deadweight' => 200.0,
                'handles_containers' => false,
                'handles_bulk_cargo' => false,
                'handles_liquid_cargo' => false,
                'handles_general_cargo' => false,
                'handles_dangerous_goods' => false,
                'handles_passengers' => true,
                'river_navigation' => true,
                'maritime_navigation' => false,
                'can_be_lead_vessel' => true,
                'can_be_in_convoy' => true,
                'max_convoy_size' => 4,
                'crew_capacity' => 10,
                'passenger_capacity' => 4,
                'fuel_capacity_liters' => 20000.0,
                'engine_configuration' => 'Triple diesel engines, 3000-4500 HP',
                'max_speed_knots' => 12.0,
                'service_speed_knots' => 8.0,
                'construction_materials' => 'Acero naval, casco reforzado para encallamientos',
                'typical_lifespan_years' => 35,
                'environmental_standards' => 'Certificación fluvial ambiental',
                'regulatory_requirements' => 'Licencia navegación fluvial',
                'maintenance_interval_months' => 6,
                'requires_dry_dock' => true,
                'dry_dock_interval_months' => 24,
                'active' => true,
                'is_common' => true,
                'is_specialized' => true,
                'display_order' => 60,
                'icon' => 'ship-tugboat-river',
                'color_code' => '#F59E0B',
            ],

            // ========== EMPUJADORES ==========
            [
                'code' => 'PUSHER_STD_001',
                'name' => 'Empujador Estándar',
                'short_name' => 'Empujador',
                'description' => 'Embarcación empujadora para formación de convoy con barcazas. Optimizada para empuje y eficiencia de combustible en trayectos largos.',
                'category' => 'pusher',
                'propulsion_type' => 'self_propelled',
                'min_length' => 35.0,
                'max_length' => 55.0,
                'min_beam' => 12.0,
                'max_beam' => 16.0,
                'min_draft' => 3.0,
                'max_draft' => 5.0,
                'min_deadweight' => 100.0,
                'max_deadweight' => 300.0,
                'handles_containers' => false,
                'handles_bulk_cargo' => false,
                'handles_liquid_cargo' => false,
                'handles_general_cargo' => false,
                'handles_dangerous_goods' => false,
                'handles_passengers' => true,
                'river_navigation' => true,
                'maritime_navigation' => true,
                'can_be_lead_vessel' => true,
                'can_be_in_convoy' => true,
                'max_convoy_size' => 8,
                'crew_capacity' => 12,
                'passenger_capacity' => 6,
                'fuel_capacity_liters' => 35000.0,
                'engine_configuration' => 'Twin diesel engines, 4000-6000 HP',
                'max_speed_knots' => 15.0,
                'service_speed_knots' => 9.0,
                'construction_materials' => 'Acero naval, proa reforzada para empuje',
                'typical_lifespan_years' => 32,
                'environmental_standards' => 'IMO Tier II emissions, sistema SCR',
                'regulatory_requirements' => 'Certificado de convoy, capacitación especializada',
                'maintenance_interval_months' => 6,
                'requires_dry_dock' => true,
                'dry_dock_interval_months' => 24,
                'active' => true,
                'is_common' => true,
                'is_specialized' => true,
                'display_order' => 70,
                'icon' => 'ship-pusher',
                'color_code' => '#059669',
            ],

            // ========== AUTOPROPULSADOS ==========
            [
                'code' => 'SELF_CARGO_001',
                'name' => 'Buque de Carga Autopropulsado',
                'short_name' => 'Autopropulsado Carga',
                'description' => 'Buque autopropulsado para carga general y contenedores. Ideal para rutas directas sin necesidad de remolque.',
                'category' => 'self_propelled',
                'propulsion_type' => 'self_propelled',
                'min_length' => 80.0,
                'max_length' => 150.0,
                'min_beam' => 15.0,
                'max_beam' => 25.0,
                'min_draft' => 4.0,
                'max_draft' => 8.0,
                'min_deadweight' => 1000.0,
                'max_deadweight' => 3000.0,
                'handles_containers' => true,
                'handles_bulk_cargo' => true,
                'handles_liquid_cargo' => false,
                'handles_general_cargo' => true,
                'handles_dangerous_goods' => true,
                'handles_passengers' => true,
                'river_navigation' => true,
                'maritime_navigation' => true,
                'can_be_lead_vessel' => true,
                'can_be_in_convoy' => false,
                'max_convoy_size' => 1,
                'crew_capacity' => 20,
                'passenger_capacity' => 12,
                'fuel_capacity_liters' => 50000.0,
                'engine_configuration' => 'Main diesel engine, 6000-10000 HP',
                'max_speed_knots' => 18.0,
                'service_speed_knots' => 14.0,
                'construction_materials' => 'Acero naval, estructura optimizada',
                'typical_lifespan_years' => 25,
                'environmental_standards' => 'IMO MARPOL Annex VI, sistema de tratamiento',
                'regulatory_requirements' => 'Certificado internacional, inspección anual',
                'maintenance_interval_months' => 8,
                'requires_dry_dock' => true,
                'dry_dock_interval_months' => 30,
                'active' => true,
                'is_common' => true,
                'is_specialized' => false,
                'display_order' => 80,
                'icon' => 'ship-cargo',
                'color_code' => '#10B981',
            ],

            // ========== MIXTOS ==========
            [
                'code' => 'MIXED_FLEXI_001',
                'name' => 'Embarcación Multifuncional',
                'short_name' => 'Multifuncional',
                'description' => 'Embarcación híbrida que puede operar como remolcador, empujador o transporte independiente según las necesidades operativas.',
                'category' => 'mixed',
                'propulsion_type' => 'hybrid',
                'min_length' => 40.0,
                'max_length' => 70.0,
                'min_beam' => 10.0,
                'max_beam' => 16.0,
                'min_draft' => 3.0,
                'max_draft' => 5.5,
                'min_deadweight' => 150.0,
                'max_deadweight' => 500.0,
                'handles_containers' => true,
                'handles_bulk_cargo' => true,
                'handles_liquid_cargo' => false,
                'handles_general_cargo' => true,
                'handles_dangerous_goods' => false,
                'handles_passengers' => true,
                'river_navigation' => true,
                'maritime_navigation' => true,
                'can_be_lead_vessel' => true,
                'can_be_in_convoy' => true,
                'max_convoy_size' => 5,
                'crew_capacity' => 15,
                'passenger_capacity' => 8,
                'fuel_capacity_liters' => 25000.0,
                'engine_configuration' => 'Hybrid diesel-electric, 3500-5000 HP',
                'max_speed_knots' => 16.0,
                'service_speed_knots' => 11.0,
                'construction_materials' => 'Acero naval modular, configuración adaptable',
                'typical_lifespan_years' => 30,
                'environmental_standards' => 'Certificación híbrida, reducción de emisiones',
                'regulatory_requirements' => 'Certificación múltiple según configuración',
                'maintenance_interval_months' => 6,
                'requires_dry_dock' => true,
                'dry_dock_interval_months' => 24,
                'active' => true,
                'is_common' => false,
                'is_specialized' => true,
                'display_order' => 90,
                'icon' => 'ship-mixed',
                'color_code' => '#8B5CF6',
            ],
        ];
    }
}