<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CargoTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * MÓDULO 3: VIAJES Y CARGAS
     * Seeder para tipos de carga más comunes en transporte fluvial/marítimo
     * Compatible con estándares internacionales y webservices AR/PY
     */
    public function run(): void
    {
        $now = Carbon::now();

        // ========================================
        // TIPOS PRINCIPALES (NIVEL 1)
        // ========================================
        
        $mainTypes = [
            // Carga General
            [
                'id' => 1,
                'code' => 'GEN001',
                'name' => 'Carga General',
                'short_name' => 'General',
                'description' => 'Mercadería diversa empacada en bultos individuales',
                'parent_id' => null,
                'level' => 1,
                'full_path' => 'Carga General',
                'cargo_nature' => 'solid',
                'packaging_type' => 'break_bulk',
                'requires_refrigeration' => false,
                'requires_special_handling' => false,
                'is_dangerous_goods' => false,
                'requires_permits' => false,
                'is_perishable' => false,
                'is_fragile' => false,
                'requires_fumigation' => false,
                'can_be_mixed' => true,
                'allows_consolidation' => true,
                'allows_deconsolidation' => true,
                'allows_transshipment' => true,
                'typical_density' => 500.000,
                'typical_loading_time' => 12,
                'webservice_code' => 'GEN',
                'active' => true,
                'is_common' => true,
                'display_order' => 10,
                'icon' => '📋',
                'color_code' => '#10B981',
                'created_date' => $now,
            ],

            // Contenedores
            [
                'id' => 2,
                'code' => 'CON001',
                'name' => 'Contenedores',
                'short_name' => 'Containers',
                'description' => 'Carga en contenedores estándar ISO',
                'parent_id' => null,
                'level' => 1,
                'full_path' => 'Contenedores',
                'cargo_nature' => 'solid',
                'packaging_type' => 'containerized',
                'requires_refrigeration' => false,
                'requires_special_handling' => false,
                'is_dangerous_goods' => false,
                'requires_permits' => false,
                'is_perishable' => false,
                'is_fragile' => false,
                'requires_fumigation' => false,
                'can_be_mixed' => true,
                'allows_consolidation' => true,
                'allows_deconsolidation' => true,
                'allows_transshipment' => true,
                'typical_density' => 800.000,
                'max_weight_per_container' => 28000.00,
                'typical_loading_time' => 2,
                'webservice_code' => 'CONT',
                'active' => true,
                'is_common' => true,
                'display_order' => 20,
                'icon' => '📦',
                'color_code' => '#3B82F6',
                'created_date' => $now,
            ],

            // Carga a Granel
            [
                'id' => 3,
                'code' => 'BLK001',
                'name' => 'Carga a Granel',
                'short_name' => 'Granel',
                'description' => 'Mercadería sin empacar transportada a granel',
                'parent_id' => null,
                'level' => 1,
                'full_path' => 'Carga a Granel',
                'cargo_nature' => 'solid',
                'packaging_type' => 'bulk',
                'requires_refrigeration' => false,
                'requires_special_handling' => true,
                'is_dangerous_goods' => false,
                'requires_permits' => false,
                'is_perishable' => false,
                'is_fragile' => false,
                'requires_fumigation' => false,
                'can_be_mixed' => false,
                'allows_consolidation' => false,
                'allows_deconsolidation' => false,
                'allows_transshipment' => true,
                'typical_density' => 1500.000,
                'typical_loading_time' => 8,
                'webservice_code' => 'BULK',
                'active' => true,
                'is_common' => true,
                'display_order' => 30,
                'icon' => '🚛',
                'color_code' => '#EF4444',
                'created_date' => $now,
            ],

            // Carga Refrigerada
            [
                'id' => 4,
                'code' => 'REF001',
                'name' => 'Carga Refrigerada',
                'short_name' => 'Refrigerada',
                'description' => 'Mercadería que requiere control de temperatura',
                'parent_id' => null,
                'level' => 1,
                'full_path' => 'Carga Refrigerada',
                'cargo_nature' => 'solid',
                'packaging_type' => 'containerized',
                'requires_refrigeration' => true,
                'requires_special_handling' => true,
                'is_dangerous_goods' => false,
                'requires_permits' => false,
                'is_perishable' => true,
                'is_fragile' => false,
                'requires_fumigation' => false,
                'temperature_range' => ['min' => -25, 'max' => 15],
                'can_be_mixed' => false,
                'allows_consolidation' => true,
                'allows_deconsolidation' => true,
                'allows_transshipment' => true,
                'typical_density' => 600.000,
                'max_weight_per_container' => 27000.00,
                'typical_loading_time' => 3,
                'webservice_code' => 'REEF',
                'active' => true,
                'is_common' => true,
                'display_order' => 40,
                'icon' => '🧊',
                'color_code' => '#06B6D4',
                'created_date' => $now,
            ],

            // Mercancías Peligrosas
            [
                'id' => 5,
                'code' => 'DNG001',
                'name' => 'Mercancías Peligrosas',
                'short_name' => 'Peligrosas',
                'description' => 'Mercadería clasificada como peligrosa según IMDG',
                'parent_id' => null,
                'level' => 1,
                'full_path' => 'Mercancías Peligrosas',
                'imdg_class' => '9',
                'cargo_nature' => 'mixed',
                'packaging_type' => 'containerized',
                'requires_refrigeration' => false,
                'requires_special_handling' => true,
                'is_dangerous_goods' => true,
                'requires_permits' => true,
                'is_perishable' => false,
                'is_fragile' => false,
                'requires_fumigation' => false,
                'requires_certificate_origin' => true,
                'requires_insurance' => true,
                'can_be_mixed' => false,
                'allows_consolidation' => false,
                'allows_deconsolidation' => false,
                'allows_transshipment' => true,
                'subject_to_inspection' => true,
                'inspection_percentage' => 25,
                'typical_density' => 700.000,
                'typical_loading_time' => 4,
                'insurance_rate' => 0.0050,
                'webservice_code' => 'DANG',
                'active' => true,
                'is_common' => true,
                'display_order' => 50,
                'icon' => '⚠️',
                'color_code' => '#F59E0B',
                'created_date' => $now,
            ],

            // Carga Líquida
            [
                'id' => 6,
                'code' => 'LIQ001',
                'name' => 'Carga Líquida',
                'short_name' => 'Líquida',
                'description' => 'Líquidos transportados en tanques o contenedores especiales',
                'parent_id' => null,
                'level' => 1,
                'full_path' => 'Carga Líquida',
                'cargo_nature' => 'liquid',
                'packaging_type' => 'bulk',
                'requires_refrigeration' => false,
                'requires_special_handling' => true,
                'is_dangerous_goods' => false,
                'requires_permits' => false,
                'is_perishable' => false,
                'is_fragile' => false,
                'requires_fumigation' => false,
                'can_be_mixed' => false,
                'allows_consolidation' => false,
                'allows_deconsolidation' => false,
                'allows_transshipment' => true,
                'typical_density' => 1000.000,
                'typical_loading_time' => 6,
                'webservice_code' => 'LIQ',
                'active' => true,
                'is_common' => true,
                'display_order' => 60,
                'icon' => '🫗',
                'color_code' => '#8B5CF6',
                'created_date' => $now,
            ],

            // Vehículos
            [
                'id' => 7,
                'code' => 'VEH001',
                'name' => 'Vehículos',
                'short_name' => 'Vehículos',
                'description' => 'Automóviles, camiones, maquinaria y equipos rodantes',
                'parent_id' => null,
                'level' => 1,
                'full_path' => 'Vehículos',
                'cargo_nature' => 'solid',
                'packaging_type' => 'ro_ro',
                'requires_refrigeration' => false,
                'requires_special_handling' => true,
                'is_dangerous_goods' => false,
                'requires_permits' => true,
                'is_perishable' => false,
                'is_fragile' => false,
                'requires_fumigation' => false,
                'requires_certificate_origin' => true,
                'can_be_mixed' => false,
                'allows_consolidation' => false,
                'allows_deconsolidation' => false,
                'allows_transshipment' => true,
                'typical_density' => 200.000,
                'typical_loading_time' => 1,
                'webservice_code' => 'RORO',
                'active' => true,
                'is_common' => true,
                'display_order' => 70,
                'icon' => '🚗',
                'color_code' => '#F59E0B',
                'created_date' => $now,
            ],

            // Gases
            [
                'id' => 8,
                'code' => 'GAS001',
                'name' => 'Gases',
                'short_name' => 'Gases',
                'description' => 'Gases comprimidos o licuados',
                'parent_id' => null,
                'level' => 1,
                'full_path' => 'Gases',
                'imdg_class' => '2',
                'cargo_nature' => 'gas',
                'packaging_type' => 'containerized',
                'requires_refrigeration' => false,
                'requires_special_handling' => true,
                'is_dangerous_goods' => true,
                'requires_permits' => true,
                'is_perishable' => false,
                'is_fragile' => false,
                'requires_fumigation' => false,
                'requires_certificate_origin' => true,
                'requires_insurance' => true,
                'can_be_mixed' => false,
                'allows_consolidation' => false,
                'allows_deconsolidation' => false,
                'allows_transshipment' => false,
                'subject_to_inspection' => true,
                'inspection_percentage' => 50,
                'typical_density' => 300.000,
                'typical_loading_time' => 3,
                'insurance_rate' => 0.0075,
                'webservice_code' => 'GAS',
                'active' => true,
                'is_common' => false,
                'display_order' => 80,
                'icon' => '🫧',
                'color_code' => '#64748B',
                'created_date' => $now,
            ],
        ];

        // ========================================
        // SUBCATEGORÍAS (NIVEL 2)
        // ========================================
        
        $subTypes = [
            // Subcategorías de Contenedores
            [
                'code' => 'CON002',
                'name' => 'Contenedor Dry 20ft',
                'short_name' => 'Dry 20',
                'description' => 'Contenedor seco estándar de 20 pies',
                'parent_id' => 2,
                'level' => 2,
                'full_path' => 'Contenedores > Contenedor Dry 20ft',
                'cargo_nature' => 'solid',
                'packaging_type' => 'containerized',
                'max_weight_per_container' => 21600.00,
                'dimension_restrictions' => ['length' => 589, 'width' => 235, 'height' => 239],
                'webservice_code' => 'DRY20',
                'active' => true,
                'is_common' => true,
                'display_order' => 21,
                'created_date' => $now,
            ],
            [
                'code' => 'CON003',
                'name' => 'Contenedor Dry 40ft',
                'short_name' => 'Dry 40',
                'description' => 'Contenedor seco estándar de 40 pies',
                'parent_id' => 2,
                'level' => 2,
                'full_path' => 'Contenedores > Contenedor Dry 40ft',
                'cargo_nature' => 'solid',
                'packaging_type' => 'containerized',
                'max_weight_per_container' => 26680.00,
                'dimension_restrictions' => ['length' => 1203, 'width' => 235, 'height' => 239],
                'webservice_code' => 'DRY40',
                'active' => true,
                'is_common' => true,
                'display_order' => 22,
                'created_date' => $now,
            ],

            // Subcategorías de Granel
            [
                'code' => 'BLK002',
                'name' => 'Granel Sólido Seco',
                'short_name' => 'Granel Seco',
                'description' => 'Cereales, minerales, fertilizantes',
                'parent_id' => 3,
                'level' => 2,
                'full_path' => 'Carga a Granel > Granel Sólido Seco',
                'cargo_nature' => 'solid',
                'packaging_type' => 'bulk',
                'requires_fumigation' => true,
                'typical_density' => 1200.000,
                'webservice_code' => 'BDRY',
                'active' => true,
                'is_common' => true,
                'display_order' => 31,
                'created_date' => $now,
            ],
            [
                'code' => 'BLK003',
                'name' => 'Granel Líquido',
                'short_name' => 'Granel Líq.',
                'description' => 'Combustibles, aceites, químicos líquidos',
                'parent_id' => 3,
                'level' => 2,
                'full_path' => 'Carga a Granel > Granel Líquido',
                'cargo_nature' => 'liquid',
                'packaging_type' => 'bulk',
                'is_dangerous_goods' => true,
                'requires_permits' => true,
                'typical_density' => 900.000,
                'webservice_code' => 'BLIQ',
                'active' => true,
                'is_common' => true,
                'display_order' => 32,
                'created_date' => $now,
            ],

            // Subcategorías de Mercancías Peligrosas
            [
                'code' => 'DNG002',
                'name' => 'Explosivos',
                'short_name' => 'Explosivos',
                'description' => 'Clase 1 IMDG - Sustancias explosivas',
                'parent_id' => 5,
                'level' => 2,
                'full_path' => 'Mercancías Peligrosas > Explosivos',
                'imdg_class' => '1',
                'cargo_nature' => 'solid',
                'packaging_type' => 'containerized',
                'is_dangerous_goods' => true,
                'requires_permits' => true,
                'requires_insurance' => true,
                'incompatible_with' => ['DNG003', 'DNG004', 'DNG005'],
                'inspection_percentage' => 100,
                'insurance_rate' => 0.0150,
                'webservice_code' => 'EXP',
                'active' => true,
                'is_common' => false,
                'display_order' => 51,
                'created_date' => $now,
            ],
            [
                'code' => 'DNG003',
                'name' => 'Gases Inflamables',
                'short_name' => 'Gas Infl.',
                'description' => 'Clase 2.1 IMDG - Gases inflamables',
                'parent_id' => 5,
                'level' => 2,
                'full_path' => 'Mercancías Peligrosas > Gases Inflamables',
                'imdg_class' => '2.1',
                'cargo_nature' => 'gas',
                'packaging_type' => 'containerized',
                'is_dangerous_goods' => true,
                'requires_permits' => true,
                'incompatible_with' => ['DNG002', 'DNG004'],
                'inspection_percentage' => 75,
                'insurance_rate' => 0.0100,
                'webservice_code' => 'GINF',
                'active' => true,
                'is_common' => false,
                'display_order' => 52,
                'created_date' => $now,
            ],

            // Subcategorías de Refrigerados
            [
                'code' => 'REF002',
                'name' => 'Congelados',
                'short_name' => 'Congelados',
                'description' => 'Productos que requieren temperaturas bajo cero',
                'parent_id' => 4,
                'level' => 2,
                'full_path' => 'Carga Refrigerada > Congelados',
                'cargo_nature' => 'solid',
                'packaging_type' => 'containerized',
                'requires_refrigeration' => true,
                'is_perishable' => true,
                'temperature_range' => ['min' => -25, 'max' => -18],
                'webservice_code' => 'FRZN',
                'active' => true,
                'is_common' => true,
                'display_order' => 41,
                'created_date' => $now,
            ],
            [
                'code' => 'REF003',
                'name' => 'Refrigerados',
                'short_name' => 'Refriger.',
                'description' => 'Productos frescos que requieren refrigeración',
                'parent_id' => 4,
                'level' => 2,
                'full_path' => 'Carga Refrigerada > Refrigerados',
                'cargo_nature' => 'solid',
                'packaging_type' => 'containerized',
                'requires_refrigeration' => true,
                'is_perishable' => true,
                'temperature_range' => ['min' => 0, 'max' => 15],
                'webservice_code' => 'REFR',
                'active' => true,
                'is_common' => true,
                'display_order' => 42,
                'created_date' => $now,
            ],
        ];

        // Insertar tipos principales
        DB::table('cargo_types')->insert($mainTypes);
        $this->command->info('✅ Tipos principales de carga creados (8 registros)');

        // Insertar subcategorías
        DB::table('cargo_types')->insert($subTypes);
        $this->command->info('✅ Subcategorías de carga creadas (8 registros)');

        $this->command->info('🎉 Total: 16 tipos de carga con jerarquía completa');
    }
}